#!/bin/bash
#
# This script is to pull all my Github repositories

_githubdir=$HOME/Github

# Change the _localdir to your local directory of Github repositories you
# want to pull
_localdir1=dotfiles
_localdir2=linux-rt-lts-manjaro
_localdir3=packages-core
_localdir4=packages-community
_localdir5=packages-extra
_localdir6=manjaro-rt

# Change the _remtarget to the remote you set for your Github repositories
# you want to pull
_remtarget1=origin
_remtarget2=origin
_remtarget3=upstream
_remtarget4=upstream
_remtarget5=upstream
_remtarget6=origin

pull_1() {
  cd ${_githubdir};
  if [ -d "${_localdir1}" ]; then
    cd $_localdir1
  else
    echo "Directory '${_localdir1}' is not found. Please make sure it exists in your ${_githubdir}"
  fi
  while true; do
    read -p -n 1  "Do you wish to pull this repository? (Y/n)" yn
    case $yn in
      [Yy]* ) git pull $_remtarget1 master; break;;
      [Nn]* ) break;;
      * ) echo "Please answer yes (Y) or no (n)";;
    esac
  done
  echo ""
  echo "Press any key to continue"
  read -s -n1
}

pull_2() {
  cd $_githubdir;
  if [ -d "$_localdir2" ]; then
    cd $_localdir2
  else
    echo "Directory '$_localdir2' is not found. Please make sure it exists in your $_githubdir"
  fi
  while true; do
    read -p "Do you wish to pull this repository? (Y/n)" yn
    case $yn in
      [Yy]* ) git pull $_remtarget2 master; break;;
      [Nn]* ) break;;
      * ) echo "Please answer yes (Y) or no (n)";;
    esac
  done
  echo ""
  echo "Press any key to continue"
  read -s -n1
}

pull_3() {
  cd $_githubdir;
  if [ -d "$_localdir3" ]; then
    cd $_localdir3
  else
    echo "Directory '$_localdir3' is not found. Please make sure it exists in your $_githubdir"
  fi
  while true; do
    read -p "Do you wish to pull this repository? (Y/n)" yn
    case $yn in
      [Yy]* ) git pull $_remtarget3 master; break;;
      [Nn]* ) break;;
      * ) echo "Please answer yes (Y) or no (n)";;
    esac
  done
  echo ""
  echo "Press any key to continue"
  read -s -n1
}

pull_4() {
  cd $_githubdir;
  if [ -d "$_localdir4" ]; then
    cd $_localdir4
  else
    echo "Directory '$_localdir4' is not found. Please make sure it exists in your $_githubdir"
  fi
  while true; do
    read -p "Do you wish to pull this repository? (Y/n)" yn
    case $yn in
      [Yy]* ) git pull $_remtarget4 master; break;;
      [Nn]* ) break;;
      * ) echo "Please answer yes (Y) or no (n)";;
    esac
  done
  echo ""
  echo "Press any key to continue"
  read -s -n1
}

pull_5() {
  cd $_githubdir;
  if [ -d "$_localdir5" ]; then
    cd $_localdir5
  else
    echo "Directory '$_localdir5' is not found. Please make sure it exists in your $_githubdir"
  fi
  while true; do
    read -p "Do you wish to pull this repository? (Y/n)" yn
    case $yn in
      [Yy]* ) git pull $_remtarget5 master; break;;
      [Nn]* ) break;;
      * ) echo "Please answer yes (Y) or no (n)";;
    esac
  done
  echo ""
  echo "Press any key to continue"
  read -s -n1
}

pull_6() {
  cd $_githubdir;
  if [ -d "$_localdir6" ]; then
    cd $_localdir6
  else
    echo "Directory '$_localdir6' is not found. Please make sure it exists in your $_githubdir"
  fi
  while true; do
    read -p "Do you wish to pull this repository? (Y/n)" yn
    case $yn in
      [Yy]* ) git pull $_remtarget6 master; break;;
      [Nn]* ) break;;
      * ) echo "Please answer yes (Y) or no (n)";;
    esac
  done
  echo ""
  echo "Press any key to continue"
  read -s -n1
}

pull_all() {
  cd $_githubdir
  if [[ -d "$_localdir1" && -d "$_localdir2" && -d "$_localdir3" && -d "$_localdir4" && -d "$_localdir5" && -d "$_localdir6" ]]; then
    while true; do
      read -p "Do you wish to pull all these repositories? (Y/n)" yn
      case $yn in
        [Yy]* )
          cd $_githubdir/$_localdir1
          git pull $_remtarget1 master
          cd $_githubdir/$_localdir2
          git pull $_remtarget2 master
          cd $_githubdir/$_localdir3
          git pull $_remtarget3 master
          cd $_githubdir/$_localdir4
          git pull $_remtarget4 master
          cd $_githubdir/$_localdir5
          git pull $_remtarget5 master
          cd $_githubdir/$_localdir6
          git pull $_remtarget6 master; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes (Y) or no (n)";;
      esac
    done
  else
    echo "One or more of the directories $_localdir1 $_localdir2 $_localdir3 $_localdir4 $_localdir5 $_localdir6 are not found."
    echo "Please make sure they exist in your $_githubdir"
  fi
  echo ""
  echo "Press any key to continue"
  read -s -n1
}

function main {
  while true; do
  clear
  echo ""
  echo -e "              ::Git Pull Settings:: "
  echo -e " ┌─────────────────────────────────────────────────┐"
  echo -e " | Please select the repository you want to pull   |"
  echo -e " |  1. dotfiles repository                         |"
  echo -e " |  2. linux-rt-lts-manjaro repository             |"
  echo -e " |  3. packages-core                               |"
  echo -e " |  4. packages-community                          |"
  echo -e " |  5. packages-extra                              |"
  echo -e " |  6. manjaro-rt                                  |"
  echo -e " |  7. "ALL" the repository above                  |"
  echo -e " └─────────────────────────────────────────────────┘"
  echo -e "         Pick your selection   -   0. EXIT "
  echo ""
  read -p "Please input your selection:" choice
  case $choice in
    1)
      pull_1
      clear
      ;;
    2)
      pull_2
      clear
      ;;
    3)
      pull_3
      clear
      ;;
    4)
      pull_4
      clear
      ;;
    5)
      pull_5
      clear
      ;;
    6)
      pull_6
      clear
      ;;
    7)
      pull_all
      clear
      ;;
    0)
      clear && exit
      ;;
    *)
      echo "Wrong input detected. Please input number 1-7." 
      clear
      ;;
  esac
done
}

main

